/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itextpdf;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
//import java.awt.Font;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author AL AMIN
 */
public class ItextTabelDatabase extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement ps = null;
    ResultSet rs = null;
    /**
     * Creates new form ItextTabelDatabase
     */
    public ItextTabelDatabase() {
        initComponents();
        dbConnection();
    }
    void dbConnection(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
           String url = "jdbc:oracl:thin:@loacalhost:1521:xe";
            conn = DriverManager.getConnection(url, "databasename","password");
            //JOptionPane.showMessageDialog(null, "Successfull");
        }catch(ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getpdf = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        getpdf.setText("get pdf");
        getpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getpdfActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(getpdf)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getpdf)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getpdfActionPerformed
       // and customer_id like'0104%'
        String sql = "select * from mst_deposit where bank_id='0' ORDER BY CUSTOMER_ID ASC";
       try{
           ps = conn.prepareStatement(sql);
           rs = ps.executeQuery();
           Document doc = new Document(PageSize.A4,5,5,5,5);
           doc.addAuthor("MD. AL AMIN");
           PdfWriter.getInstance(doc, new FileOutputStream("deposit.pdf"));
           doc.open();
           Font f1 = new Font(Font.FontFamily.HELVETICA,15,Font.BOLD,BaseColor.BLACK);
           Paragraph p = new Paragraph("JALALABAD GAS TRANSMISSION AND DISTRIBUTION SYSTEM LTD.",f1);
           p.setAlignment(Element.ALIGN_CENTER);
           doc.add(p);
           
           Font f2 = new Font(Font.FontFamily.HELVETICA,13,Font.UNDERLINE);
           Paragraph p1 = new Paragraph("(A COMPANY OF PETROBANGLA)",f2);
           p1.setAlignment(Element.ALIGN_CENTER);
           doc.add(p1);
           
           Paragraph d = new Paragraph("ALL BANK GUARANTEE");
           d.setAlignment(Element.ALIGN_CENTER);
           doc.add(d);
           doc.add(new Paragraph(" "));
           
           PdfPTable table = new PdfPTable(6);
           table.setWidthPercentage(100);
           table.setTotalWidth(new float[] {15,30,30,30,30,30});
           DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
           
           PdfPCell cell = new PdfPCell(new Phrase("SL No"));
           //cell.setBorderWidth(1);
           //cell.setBorderWidthTop(1);
           cell.setHorizontalAlignment(Element.ALIGN_CENTER);
           table.addCell(cell);
           
           table.addCell("Customer ID");
           table.addCell("Deposit Date");
           table.addCell("VALID FROM");
           table.addCell("VALID TO");
           table.addCell("Deposit Amount");
           int counter=1;
           while(rs.next()){
               
               String str = Integer.toString(counter);
               PdfPCell cell1 = new PdfPCell(new Paragraph(str));
               cell1.setHorizontalAlignment(Element.ALIGN_CENTER);
               cell1.setVerticalAlignment(Element.PTABLE);
               table.addCell(cell1);
               
               table.addCell(rs.getString("customer_id"));
               table.addCell(rs.getString("deposit_date"));
               table.addCell(rs.getString("VALID_FROM"));
               table.addCell(rs.getString("VALID_TO"));
               table.addCell(rs.getString("total_deposit"));
               counter++;
           }
           doc.add(table);
           doc.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(this, e);
       }
    }//GEN-LAST:event_getpdfActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItextTabelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItextTabelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItextTabelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItextTabelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItextTabelDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getpdf;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
