/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package itextpdf;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.List;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.util.Date;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author AL AMIN
 */
public class Pdf1 extends javax.swing.JFrame {

    /**
     * Creates new form Pdf1
     */
    public Pdf1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        export1 = new javax.swing.JButton();
        iTextFont = new javax.swing.JButton();
        itextDate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        iTextTable = new javax.swing.JButton();
        iTextTableTitleandcolor = new javax.swing.JButton();
        addImage = new javax.swing.JButton();
        iTextList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("iText Java Prectice ");

        export1.setBackground(new java.awt.Color(255, 51, 51));
        export1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        export1.setText("Pdf 1");
        export1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export1ActionPerformed(evt);
            }
        });

        iTextFont.setBackground(new java.awt.Color(255, 51, 51));
        iTextFont.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iTextFont.setText("iText Font");
        iTextFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTextFontActionPerformed(evt);
            }
        });

        itextDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        itextDate.setText("iText Date");
        itextDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itextDateActionPerformed(evt);
            }
        });

        jLabel2.setText("https://www.youtube.com/watch?v=kBPzwalqWFQ&list=PLS1QulWo1RIayTWHnCGE_ttQG1_ajCBI4&index=7");

        iTextTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iTextTable.setText("iText Table");
        iTextTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTextTableActionPerformed(evt);
            }
        });

        iTextTableTitleandcolor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iTextTableTitleandcolor.setText("iText Table Title and Color");
        iTextTableTitleandcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTextTableTitleandcolorActionPerformed(evt);
            }
        });

        addImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addImage.setText("iText Image");
        addImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageActionPerformed(evt);
            }
        });

        iTextList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        iTextList.setText("iText List");
        iTextList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iTextListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iTextList)
                    .addComponent(addImage)
                    .addComponent(iTextTableTitleandcolor)
                    .addComponent(iTextTable)
                    .addComponent(itextDate)
                    .addComponent(iTextFont)
                    .addComponent(export1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(export1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iTextFont)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itextDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iTextTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iTextTableTitleandcolor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iTextList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void export1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export1ActionPerformed
        try{
            Document doc = new Document(PageSize.A4);
            doc.addAuthor("MD. AL AMIN");
            doc.addTitle("New Report");
            
            PdfWriter.getInstance(doc, new FileOutputStream("report1.pdf"));
            doc.open();
            doc.add(new Paragraph("Hello world"));
            
            doc.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_export1ActionPerformed

    private void iTextFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTextFontActionPerformed
        try{
            Document doc = new Document(PageSize.A4);
            PdfWriter.getInstance(doc, new FileOutputStream("itextfont.pdf"));
            
            doc.open();
            doc.add(new Paragraph("Hello iText FOnt",FontFactory.getFont(FontFactory.TIMES_BOLD, 48,Font.ITALIC, BaseColor.GREEN)));
            doc.add(new Paragraph("Leading University Sylhet", FontFactory.getFont(FontFactory.HELVETICA,24)));
            doc.close();
            JOptionPane.showMessageDialog(null, "Report Created Successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_iTextFontActionPerformed

    private void itextDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itextDateActionPerformed
        try{
            Document doc = new Document(PageSize.A4);
            doc.addAuthor("MD. AL AMIN");
            doc.addTitle("Java Itext Date");
            
            PdfWriter.getInstance(doc, new FileOutputStream("itextdate.pdf"));
            doc.open();
            doc.add(new Paragraph("Leading University, Sylhet",FontFactory.getFont(FontFactory.HELVETICA,20,Font.BOLD)));
            doc.add(new Paragraph(new Date().toString()));
            
            doc.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_itextDateActionPerformed

    private void iTextTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTextTableActionPerformed
        try{
            Document doc = new Document(PageSize.A4);
            doc.addAuthor("MD. AL AMIN");
            doc.addTitle("Table of Itext");
            
            PdfWriter.getInstance(doc, new FileOutputStream("itexttable.pdf"));
            doc.open();
            doc.add(new Paragraph("Leading University, Sylhet",FontFactory.getFont(FontFactory.HELVETICA,20,Font.BOLD,BaseColor.RED)));
            doc.add(new Paragraph(new Date().toString()));
            doc.add(new Paragraph("---------------------------------------------------------------------------------"));
            // add table
            PdfPTable table = new PdfPTable(4);
            table.addCell("SL");
            table.addCell("Name");
            table.addCell("Roll");
            table.addCell("Address");
            table.addCell(" ");
            table.addCell("Al amin");
            table.addCell("343");
            table.addCell("sylhet");
            doc.add(table);
            
            doc.close();
            JOptionPane.showMessageDialog(null, "Report Saved");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_iTextTableActionPerformed

    private void iTextTableTitleandcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTextTableTitleandcolorActionPerformed
        try{
            Document doc = new Document(PageSize.A4);
            doc.addAuthor("MD. AL AMIN");
            doc.addTitle("Color Table");
            PdfWriter.getInstance(doc, new FileOutputStream("colortable.pdf"));
            
            doc.open();
            doc.add(new Paragraph("Jalalabad Gas Transmission and Distribution System Ltd.",FontFactory.getFont(FontFactory.HELVETICA,18,Font.BOLD)));
            doc.add(new Paragraph(new Date().toLocaleString()));
            doc.add(new Paragraph("-------------------------------------------------------------------------------"));
            
            //add table 
            PdfPTable table = new PdfPTable(3);
            // start table title section
            PdfPCell cell = new PdfPCell(new Paragraph("Table Title",FontFactory.getFont(FontFactory.COURIER,18,Font.BOLD, BaseColor.GREEN)));
            cell.setColspan(3);
            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
            cell.setBackgroundColor(BaseColor.DARK_GRAY);
            cell.setBorderWidth(TOP_ALIGNMENT);
            cell.setBorder(2);
            table.addCell(cell);
            //end table title section 
            
            table.addCell(new Paragraph("SL No",FontFactory.getFont(FontFactory.COURIER,12,Font.BOLD)));
            table.addCell("Name");
            table.addCell("Roll");
            doc.add(table);
            doc.add(new Paragraph("Hello "));
            doc.close();
            JOptionPane.showConfirmDialog(null, "Report Saved");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_iTextTableTitleandcolorActionPerformed

    private void addImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageActionPerformed
        try{
            Document doc = new Document(PageSize.A4);
            
            PdfWriter.getInstance(doc, new FileOutputStream("image.pdf"));
            doc.open();
            Image image = Image.getInstance("jgtdsl.jpg");
            doc.add(image);
            doc.add(new Paragraph("JALALABAD GAS T & D SYSTEM LTD.", FontFactory.getFont(FontFactory.HELVETICA,18,Font.BOLD)));
            doc.add(new Paragraph(new Date().toLocaleString()));
            doc.add(new Paragraph("--------------------------------------------------"));
            PdfPTable table = new PdfPTable(3);
            table.addCell("Name");
            table.addCell("Roll");
            table.addCell("Dept");
            table.addCell("AL AMIN");
            table.addCell("766855");
            table.addCell("621577");
            doc.add(table);
            doc.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addImageActionPerformed

    private void iTextListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iTextListActionPerformed
        try{
            Document doc = new Document();
            doc.addAuthor("MD. AL AMIN");
            doc.addTitle("iText List");
            PdfWriter.getInstance(doc, new FileOutputStream("itextlist.pdf"));
            doc.open();
            Image image = Image.getInstance("jgtdsl.jpg");
            doc.add(image);
            doc.add(new Paragraph("Jalalabad Gas T & D System Ltd.",FontFactory.getFont(FontFactory.HELVETICA,18,Font.BOLD,BaseColor.DARK_GRAY)));
            doc.add(new Paragraph(new Date().toGMTString()));
            doc.add(new Paragraph("--------------------------------------------------------------------"));
            
            PdfPTable table = new PdfPTable(3);
            PdfPCell cell = new PdfPCell(new Paragraph("Customer List of JGTDSL",FontFactory.getFont(FontFactory.HELVETICA,14,Font.BOLD)));
            cell.setColspan(3);
            doc.add(cell);
            table.addCell("Code");
            table.addCell("Name");
            table.addCell("Email");
            
            table.addCell("030700001");
            table.addCell("MD. AL AMIN");
            table.addCell("aminspicse@gmail.com");
            doc.add(table);
            
            // List 
            
            List list = new List();
            list.add("Item 1");
            list.add("Item 2");
            list.add("Item 3");
            doc.add(list);
            
            List ls = new List(true,10);
            ls.add("Item list 1");
            ls.add("Item list 2");
            ls.add("Item List 3");
            doc.add(ls);
            
            doc.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_iTextListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pdf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pdf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pdf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pdf1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pdf1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImage;
    private javax.swing.JButton export1;
    private javax.swing.JButton iTextFont;
    private javax.swing.JButton iTextList;
    private javax.swing.JButton iTextTable;
    private javax.swing.JButton iTextTableTitleandcolor;
    private javax.swing.JButton itextDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
